# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\"2\n\x0f\x43\x61rNotification\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08userName\x18\x02 \x01(\t\" \n\x08\x43\x61rReply\x12\x14\n\x0coffendingCar\x18\x01 \x01(\x08\x32\x39\n\x0cNotification\x12)\n\x08\x43\x61rAlert\x12\x10.CarNotification\x1a\t.CarReply\"\x00\x42\x10Z\x0e./notificationb\x06proto3')



_CARNOTIFICATION = DESCRIPTOR.message_types_by_name['CarNotification']
_CARREPLY = DESCRIPTOR.message_types_by_name['CarReply']
CarNotification = _reflection.GeneratedProtocolMessageType('CarNotification', (_message.Message,), {
  'DESCRIPTOR' : _CARNOTIFICATION,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:CarNotification)
  })
_sym_db.RegisterMessage(CarNotification)

CarReply = _reflection.GeneratedProtocolMessageType('CarReply', (_message.Message,), {
  'DESCRIPTOR' : _CARREPLY,
  '__module__' : 'notification_pb2'
  # @@protoc_insertion_point(class_scope:CarReply)
  })
_sym_db.RegisterMessage(CarReply)

_NOTIFICATION = DESCRIPTOR.services_by_name['Notification']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./notification'
  _CARNOTIFICATION._serialized_start=22
  _CARNOTIFICATION._serialized_end=72
  _CARREPLY._serialized_start=74
  _CARREPLY._serialized_end=106
  _NOTIFICATION._serialized_start=108
  _NOTIFICATION._serialized_end=165
# @@protoc_insertion_point(module_scope)
